name: Mat Gargano
markdown: kramdown
exclude: ['.sass-cache', 'node_modules', 'sass', 'Gruntfile.js', 'README.md', 'bower.json', 'package.json', 'js/plugins']

---
layout: default
title: Mat Gargano.com
icons:
    - link: https://github.com/matgargano
      class: fa fa-github
    - link: https://linkedin.com/in/matgargano
      class: fa fa-linkedin
    - link: https://profiles.wordpress.org/matstars
      class: fa fa-wordpress

sections:
    - title: header
      template: header.html

    - title: body
      template: body.html

    - title: footer
      template: footer.html




sections:
    - title: header
      template: header.html

    - title: body
      template: body.html

    - title: footer
      template: footer.html
